### ISSUE TITLE
Accuracy of repo name and description

### ISSUE THREAD

**Issue by jasonkiss** [GOVTNZ/public-sector-websites#1]
Is this a list of domains (which may or may not be associated with websites), or a list of websites, in which case "domains" is somewhat inaccurate?

**Comment by camfindlay** [comment]
Good point @jasonkiss - would 1 website be at 1 domain? We could always rename the repo to something like "public-sector-websites"?

**Comment by camfindlay** [comment]
updated.

**Comment by jasonkiss** [comment]
WFM. Ta.
